### ISSUE TITLE
Roulette

### ISSUE THREAD

**Issue by tehdragonfly** [MSPARP/newparp#7]
AKA "For trademark reasons we can't call it Trollplay" mode

**Comment by tehdragonfly** [comment]
Current status:
* Need to make disconnections clearer. Possibly ditch the user list entirely and show "▼ is online/offline." in the same space where typing notifications will go, like on Cherubplay.

**Comment by nadiaff** [comment]
I like this idea since we don't really need the user list anyway

All the sidebar needs is a way to access the character settings options and maybe the other settings options. Also, there should be a way to block the other user if you don't want to run into them again, but that can be a button somewhere, possibly that appears when you end the chat.

**Comment by tehdragonfly** [comment]
The sidebar thing is done in 49f23af.

**Comment by tehdragonfly** [comment]
Blocking is #53 so this is done.
